import { expect, test } from "@playwright/test"

test("starts with the filter focused and filters Tabler icons as you type", async ({ page }) => {
  await page.goto("/")
  const filter = page.getByRole("searchbox", { name: "Filter icons" })
  await expect(filter).toBeFocused()
  await page.keyboard.type("arrow left")
  await expect(page.getByRole("button", { name: "Copy arrow-left", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Copy alarm", exact: true })).toHaveCount(0)
})

test("finds related concepts and prioritizes complete icon-name words", async ({ page }) => {
  await page.goto("/")
  const filter = page.getByRole("searchbox", { name: "Filter icons" })
  await filter.fill("data")
  await expect(page.getByRole("button", { name: "Copy table", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Copy chart-bar", exact: true })).toBeVisible()
  await filter.fill("ai")
  const names = await page
    .getByRole("button", { name: /^Copy / })
    .evaluateAll(buttons => buttons.map(button => button.getAttribute("aria-label")))
  expect(names[0]).toBe("Copy ai")
  expect(names.indexOf("Copy bookmark-ai")).toBeLessThan(names.indexOf("Copy mail-opened-filled"))
  await page.getByRole("combobox", { name: "Icon set" }).selectOption("lucide")
  await filter.fill("spreadsheet")
  await expect(page.getByRole("button", { name: "Copy table", exact: true })).toBeVisible()
})

test("remembers the global icon set after reloading", async ({ page }) => {
  await page.goto("/")
  const selector = page.getByRole("combobox", { name: "Icon set" })
  await expect(selector).toHaveValue("tabler")
  await selector.selectOption("lucide")
  await page.reload()
  await expect(selector).toHaveValue("lucide")
  await expect(page.getByRole("searchbox", { name: "Filter icons" })).toBeFocused()
  await page.keyboard.type("alarm clock")
  await expect(page.getByRole("button", { name: "Copy alarm-clock", exact: true })).toBeVisible()
})

test("uses Tabler when the stored set is invalid or storage is unavailable", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("icons:set", "obsolete"))
  await page.goto("/")
  await expect(page.getByRole("combobox", { name: "Icon set" })).toHaveValue("tabler")
  await page.addInitScript(() => {
    Object.defineProperty(Storage.prototype, "getItem", {
      value() {
        throw new Error("Blocked")
      },
    })
    Object.defineProperty(Storage.prototype, "setItem", {
      value() {
        throw new Error("Blocked")
      },
    })
  })
  await page.reload()
  await page.getByRole("combobox", { name: "Icon set" }).selectOption("heroicons")
  await expect(page.getByRole("searchbox", { name: "Filter icons" })).toBeFocused()
  await page.keyboard.type("academic")
  await expect(page.getByRole("button", { name: "Copy academic-cap", exact: true })).toBeVisible()
})

test("copies an icon name on click and returns to filtering with keyboard shortcuts", async ({
  page,
  context,
}) => {
  await context.grantPermissions(["clipboard-read", "clipboard-write"])
  await page.goto("/")
  const filter = page.getByRole("searchbox", { name: "Filter icons" })
  await filter.fill("arrow-left")
  await page.getByRole("button", { name: "Copy arrow-left", exact: true }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe("arrow-left")
  await expect(page.getByText("Copied arrow-left", { exact: true })).toBeVisible()
  await expect(page.getByText("Copied arrow-left", { exact: true })).toBeHidden()
  await page.keyboard.press("/")
  await expect(filter).toBeFocused()
  await page.keyboard.press("Escape")
  await expect(filter).toHaveValue("")
  await filter.fill("there-is-no-icon-named-this")
  await expect(page.getByText("No icons found")).toBeVisible()
  await page.getByText("Clear filter", { exact: true }).click()
  await expect(filter).toBeFocused()
})

test("applies the chosen icon color across collections", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("button", { name: "Icon color", exact: true }).click()
  const picker = page.getByRole("textbox", { name: "Hex color" })
  await expect(picker).toHaveValue("#454545")
  await page.getByRole("searchbox").fill("arrow-left")
  const icon = page.getByRole("button", { name: "Copy arrow-left", exact: true })
  await picker.fill("#cc3366")
  await expect(icon).toHaveCSS("color", "rgb(204, 51, 102)")
  await picker.press("Escape")
  await icon.hover()
  await expect(icon).toHaveCSS("color", "rgb(204, 51, 102)")
  await page.getByRole("combobox", { name: "Icon set" }).selectOption("lucide")
  await expect(icon).toHaveCSS("color", "rgb(204, 51, 102)")
})

test("chooses Tailwind shades and accepts custom hex colors", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("searchbox").fill("arrow-left")
  const icon = page.getByRole("button", { name: "Copy arrow-left", exact: true })
  const trigger = page.getByRole("button", { name: "Icon color", exact: true })
  await trigger.click()
  const hex = page.getByRole("textbox", { name: "Hex color" })
  await expect(hex).toBeFocused()
  await page.getByRole("button", { name: "blue-500", exact: true }).click()
  await expect(hex).toHaveValue("#2b7fff")
  await expect(icon).toHaveCSS("color", "rgb(43, 127, 255)")
  await hex.fill("invalid")
  await hex.press("Enter")
  await expect(hex).toHaveAttribute("aria-invalid", "true")
  await expect(icon).toHaveCSS("color", "rgb(43, 127, 255)")
  await hex.fill("abc")
  await hex.press("Enter")
  await expect(hex).toHaveValue("#aabbcc")
  await expect(icon).toHaveCSS("color", "rgb(170, 187, 204)")
  await hex.press("Escape")
  await expect(trigger).toBeFocused()
})

test("resizes icons with discrete size options", async ({ page }) => {
  await page.goto("/")
  const sizes = page.getByRole("radiogroup", { name: "Icon size" })
  await expect(sizes.getByRole("radio", { name: "48px", exact: true })).toBeChecked()
  await page.getByRole("searchbox").fill("arrow-left")
  const icon = page.getByRole("button", { name: "Copy arrow-left", exact: true }).locator("svg")
  await expect(icon).toHaveCSS("width", "48px")
  await sizes.getByRole("radio", { name: "72px", exact: true }).check()
  await expect(page.getByText("72px", { exact: true })).toBeVisible()
  await expect(icon).toHaveCSS("width", "72px")
  await sizes.getByRole("radio", { name: "72px", exact: true }).press("ArrowLeft")
  await expect(sizes.getByRole("radio", { name: "64px", exact: true })).toBeChecked()
  await expect(icon).toHaveCSS("width", "64px")
})

test("adjusts Tabler outline stroke from 1 to 2", async ({ page }) => {
  await page.goto("/")
  await page.getByRole("searchbox").fill("arrow-left")
  const strokes = page.getByRole("radiogroup", { name: "Stroke" })
  const path = page.getByRole("button", { name: "Copy arrow-left", exact: true }).locator("path")
  await expect(strokes.getByRole("radio", { name: "2", exact: true })).toBeChecked()
  await expect(path).toHaveCSS("stroke-width", "2px")
  await strokes.getByRole("radio", { name: "1", exact: true }).check()
  await expect(path).toHaveCSS("stroke-width", "1px")
  await strokes.getByRole("radio", { name: "1", exact: true }).press("ArrowRight")
  await expect(path).toHaveCSS("stroke-width", "1.25px")
  await page.getByRole("searchbox").fill("apple-filled")
  const filled = page
    .getByRole("button", { name: "Copy apple-filled", exact: true })
    .locator("path")
  await expect(filled).toHaveCSS("fill", "rgb(69, 69, 69)")
  await expect(filled).toHaveCSS("stroke", "none")
  await page.getByRole("searchbox").fill("arrow-left")
  await expect(path).toHaveCSS("stroke-width", "1.25px")
  await strokes.getByRole("radio", { name: "2", exact: true }).check()
  await expect(path).toHaveCSS("stroke-width", "2px")
})

test("uses mobile settings to adjust icons and remembers the chosen collection", async ({
  page,
}) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto("/")
  const filter = page.getByRole("searchbox", { name: "Filter icons" })
  await expect(filter).toBeFocused()
  const header = page.getByRole("banner")
  const initialPosition = await header.boundingBox()
  await page.evaluate(() => window.scrollTo(0, 1000))
  await expect.poll(async () => (await header.boundingBox())?.y).toBe(initialPosition?.y)
  await expect(filter).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  await filter.fill("arrow-left")
  const icon = page.getByRole("button", { name: "Copy arrow-left", exact: true })
  const settings = page.getByRole("button", { name: "Settings", exact: true })
  await settings.click()
  await page.getByRole("radio", { name: "64px", exact: true }).click({ position: { x: 15, y: 5 } })
  await expect(icon.locator("svg")).toHaveCSS("width", "64px")
  await page
    .getByRole("radiogroup", { name: "Stroke" })
    .getByRole("radio", { name: "1.5", exact: true })
    .check()
  await expect(icon.locator("path")).toHaveCSS("stroke-width", "1.5px")
  await page.getByRole("button", { name: "Icon color", exact: true }).click()
  await page.getByRole("button", { name: "blue-500", exact: true }).click()
  await expect(icon).toHaveCSS("color", "rgb(43, 127, 255)")
  await page.keyboard.press("Escape")
  await expect(page.getByRole("combobox", { name: "Icon set" })).toBeVisible()
  await page.keyboard.press("Escape")
  await expect(settings).toBeFocused()
  await settings.click()
  await expect(page.getByRole("radio", { name: "64px", exact: true })).toBeChecked()
  await page.getByRole("combobox", { name: "Icon set" }).selectOption("lucide")
  await page.reload()
  await expect(filter).toBeFocused()
  await settings.click()
  await expect(page.getByRole("combobox", { name: "Icon set" })).toHaveValue("lucide")
})
